#0
CACHECOLORING:  1b          [M]
MEMBANDWIDTH:   1b          [M]
BUDGET:         10000       [O]
PERIOD:         50          [O]
REPLENISHMENT:  1000        [O]

#1
APP:            READ
SIZE:           1500000
STRIDE:         64
LIMIT:          5000

#2
APP:            WRITENEON
SIZE:           1500000
STRIDE:         64

#3
APP:            WRITENEON
SIZE:           1500000
STRIDE:         64

#4
APP:            WRITENEON
SIZE:           1500000
STRIDE:         64

