/*
 * Developed by Diogo Cochicho
 */

#include <dlfcn.h>
#include <unistd.h>

#include "global.h"

ARCH SELECTED_ARCH;
ARCH_LIST AVAIL_ARCHS;

FCONFIG_LIST AVAIL_CONFIGS;

T_VOID *MODULE_HANDLE;
CONFIG *MODULE_CONFIG;

T_VOID (*BUILD_PROJECT)(CONFIG *);
T_VOID (*INIT_BENCH)(T_VOID);
RESULT *(*RUN_BENCH)(T_VOID);
T_VOID (*EXIT_BENCH)(T_VOID);

